First stab at fixing typing
Problems remaining:
1. Inconsistent types
2. Mismatch between Onyx types and what's actually sent, and my code
   based on what's actually sent doesn't account for bad types:

```
> new.expensify@1.4.36-5 typecheck
> tsc

src/components/ReportActionItem/MoneyRequestView.tsx:159:109 - error TS2345: Argument of type 'OnyxEntry<Policy>' is not assignable to parameter of type 'Policy'.
  Type 'null' is not assignable to type 'Policy'.

159             IOU.updateMoneyRequestBillable(transaction?.transactionID ?? '', report?.reportID, newBillable, policy, policyTags, policyCategories);
                                                                                                                ~~~~~~

Found 1 error in src/components/ReportActionItem/MoneyRequestView.tsx:159
```

It's never actually null, it's empty object

3. Need to double-check that everything is set by default when it needs
   to be