fix: invalid `package-lock.json` diff due to node bug
Error: Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.

from https://github.com/Expensify/App/actions/runs/25609445372/job/75176984416?pr=88110